name: upload to S3
on:
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup env
        run: npm i

      - name: Build code
        run: npm run make-webpack
        env:
          GOOGLE_CLIENT_ID: ""
          GOOGLE_CLIENT_SECRET: ""
          GOOGLE_API_KEY: ""
          BASE_URL: ""
          SESSION_SECRET: not-so-secret
          REDISCLOUD_URL: ""
          USE_STANDALONE_PYRET: true
          PYRET_RELEASE_BASE: "/js"
          CURRENT_PYRET_RELEASE: ""
          PYRET: "./js/cpo-main.jarr"
          NODE_ENV: production
          OK_GOOGLE_IDS: ""
          FIREBASE_API_KEY: ""
          FIREBASE_AUTH_DOMAIN: ""
          FIREBASE_DB_URL: ""
          FIREBASE_BUCKET: ""
          FIREBASE_SENDER_ID: ""

      - name: Link pyret
        run: ln -s node_modules/pyret-lang pyret

      - name: Build
        run: npm run build

      - name: Deploy to S3
        run: ./s3-upload.sh "${{ secrets.ASSETS_UPLOADER_KEY }}" "${{ secrets.ASSETS_UPLOADER_SECRET }}"
