name: publish docs
on:
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup env
        run: npm i

      - name: copy env
        run: cp .env.codio .env

      - name: Build
        run: npm run build
        env:
          NODE_ENV: production

      - name: Deploy to S3
        run: ./s3-upload.sh "${{ secrets.ASSETS_UPLOADER_KEY }}" "${{ secrets.ASSETS_UPLOADER_SECRET }}"
